name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        mkdir -p dist
        cp -r src dist/
        cp -r js dist/
        cp -r css dist/
        cp -r images dist/
        cp index.html dist/
        cp styles.css dist/ 