name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Verify Repository
      run: |
        echo "Verifying repository structure..."
        [ -f index.html ] && echo "index.html exists" || exit 1
        [ -d src ] && echo "src directory exists" || exit 1
        [ -d js ] && echo "js directory exists" || exit 1
        echo "Repository structure verified successfully" 